### ISSUE TITLE
Halaman Admin (CMS) untuk Klimatologi

### ISSUE THREAD

**Issue by widoyo** [widoyo/ffwsv2#6]
[Bagian Authentikasi ini](https://github.com/widoyo/ffwsv2/blob/98b2193ae0a2572727d11545d122c95c674b8ac9/main.py#L286) perlu diubah `bendungan` menjadi `klimatologi`.

## Form Input (URL: `/adm/klimatologi/add`)

1.  `curah hujan` (mm), 
2.  `Kec Angin` (km/24jam), 
3.  `Temp Min, Temp Max` (derajat Celcius), 
4.  `Kelembaban` (%)

## List Data (URL: `/adm/klimatologi`

1.  Kolom sesuaikan dg kolom di atas (Form)
2.  Fasilitas Inline Edit

**Comment by asnanzulfikar** [comment]
untuk desain database input data klimatologi belakangan ya pak? yg penting form input nya dulu begitu ?

**Comment by widoyo** [comment]
Saya siapkan table Klimatologi. Nanti di update di sini

**Comment by widoyo** [comment]
Tambahan kolom:

5.  Lama Penyinaran (menit)
6.  Penguapan (mm/hari)

**Comment by widoyo** [comment]
```
create table klimatologi (
  id int(11) auto_increment primary key, 
  agent_id int(11) NOT NULL, 
  sampling datetime NOT NULL, 
  ch_m float, 
  temp_min_m float, 
  temp_max_m float, 
  humi_m float, 
  penyinaran_m int(11), 
  penguapan_m float, 
  cuser varchar(15), 
  cdate DATETIME default NOW(), 
  muser varchar(15), 
  mdate DATETIME
);
```

**Comment by widoyo** [comment]
`ALTER TABLE klimatologi ADD COLUMN kec_angin_m FLOAT AFTER humi_m;`

**Comment by widoyo** [comment]
`ALTER TABLE klimatologi RENAME klimatmanual;`

**Comment by widoyo** [comment]
#5
